[package]
name = "todo4agent"
version = "1.0.0-beta.7"
description = "为Agent设计的MCP任务清单，附带UI界面。"
authors = ["BlazeSnow"]
edition = "2021"
rust-version = "1.85.1"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
axum = { version = "0.8", default-features = false, features = ["form", "http1", "json", "matched-path", "original-uri", "query", "tokio", "tower-log"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "time"] }
rusqlite = { version = "0.40", features = ["bundled"] }
tower-http = { version = "0.7", features = ["fs"] }
tower = { version = "0.5", features = ["util"] }
chrono = { version = "0.4" }
dirs = "7"
rust-embed = { version = "8", features = ["mime-guess"] }
sha2 = "0.11"
rand = "0.10"
fluent-i18n = "0.1.0"
